language: node_js
node_js:
  - node
script:
  - npm lint
  - npm test:ci
before_deploy:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN
  on:
    branch: master
